### ISSUE TITLE
How to calculate the GED

### ISSUE THREAD

**Issue by Nilser3** [soumickmj/PULASki#1]
Hi @soumickmj 

I read your very interesting articles, 
thanks for this interesting work and approach PULASki

I would like to know how can I calculate the GED?

Thank you very much,

Best, 

Nilser

**Comment by soumickmj** [comment]
Dear @Nilser3 
Thank you for your appreciation. 
Please accept our apologies for getting back to you so late.

You can have a look at this line:
https://github.com/soumickmj/PULASki/blob/cd6ab2c1033d7503b658fee9d82bca5402867f59/pipeline.py#L877

In https://github.com/soumickmj/PULASki/blob/master/Models/ProbUNetV2/eval.py
you would find the required functions calc_energy_distances, get_energy_distance_components.

Please feel free to get back to me if you need anything else. 

Cheers,
Soumick
