### ISSUE TITLE
where is the get_mode_statistics

### ISSUE THREAD

**Issue by JMZhou123** [soumickmj/PULASki#2]
Hello!! thank you for providing the codes about GED! But I found that the function "get_mode_statistics" in the GED can't be found. Could you please tell me where I can find it?

**Comment by soumickmj** [comment]
Hello @JMZhou123 
Please accept my apologies for this late answer. Not sure if it's still helpful (and I hope you have already found it), the "get_mode_statistics" function is available inside the Models/ProbUNetV2/eval.py file, line 133.

**Comment by JMZhou123** [comment]
Thank you！

Soumick Chatterjee, PhD ***@***.***>于2024年11月13日 周三22:54写道：
